### PR TITLE
Fix pathing issue + Allure diff screenshot fix + fix warnings

### PR DESCRIPTION
**Pull request by ashiots2**
Fixed pathing issue where when codecept is started from directory other than test root, baseFolder would not be found
Replace fs.writeFile with fs.writeFileSync to ensure the diff image is written before attached to allure.
Fix JSDoc warnings
Fix "err" scoping warning
Change undefined checks to check if element is either null or undefined
Remove unused parameter
Add check to ensure size is populated
fix overcomplicated ternary statement

### CODE REVIEW

**Comment by ashiots2** [comment]
hey, did a last minute push to update variable names and error message for mismatching image sizes so that feedback is easier to work with

**Comment by puneet0191** [comment]
@ashiots2 try the new version and let me know if you find any issues `1.8.0`

**Comment by gtycherry** [comment]
Hi @puneet0191 , @ashiots2 

I ran into the same issue, the diff image can't be added in the allure report. Could you please help to suggest what I can do if i want to see the diff in allure report? Please help to suggest. thanks.
image

Below is my package.json

image

**Comment by ashiots2** [comment]
hey @gtycherry, I am a bit confused, under the "I see visual diff" step (that failed), I can see it has 3 attachments as expected (base, actual and diff). Therefore you should be able to see it once you expand that step in allure. Does that make sense or have I misunderstood your problem?

**Comment by gtycherry** [comment]
Hi @ashiots2  Yes, My fault, there are 3 screenshot attached. thanks.

**Pull request merged**
